### ISSUE TITLE
can I have a sample ppt you created via gpt?

### ISSUE THREAD

**Issue by AbubakrChan** [MSSRPRAD/ppt-api#1]
Hey 

can I have a sample ppt you created via gpt?

Thank you

**Comment by MSSRPRAD** [comment]
Hey! Sorry I don't have any of the ppts saved. They are very plain ones with just a Title and bullet points under it. Could not add any features since my free token expired just when I had gotten a minimal example running :clown_face: 

If you are interested you can modify the `ppt.ppt()` function by giving a dummy json and seeing the ppt created.
